site_name: "GLIL"
site_author: k.koide
repo_url: https://github.com/koide3/glil_ros
site_description: "GLIL: Robust 3D Localization on a Prior Environmental Map"

markdown_extensions:
    - meta
    - attr_list
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - fontawesome_markdown

theme:
    name: material
    palette:
        primary: indigo
    front:
        text: Roboto

use_directory_urls: false


copyright: Copyright &copy; 2021 - 2022 Kenji Koide
extra:
    social:
        - icon: material/home
          link: https://staff.aist.go.jp/k.koide/
        - icon: fontawesome/brands/github
          link: https://github.com/koide3/glil_ros
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/k_koide3

extra_css:
    - "css/custom.css"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

nav:
    - 'index.md'
    - 'dependencies.md'
    - 'installation.md'
    - 'quickstart.md'
    - 'initialization.md'
    - 'viewers.md'
    - 'params_brief.md'
    - 'params_detail.md'
    - 'extend.md'
    - 'unsupported.md'
    - 'faq.md'
